module.exports.Male = {
  'Black Skeleton Mask': [
    'Orange Goggles',
    'Male Glow Glasses',
    'Reflective Glasses',
    'Cyclop Glasses',
    'Red Balaclava',
  ],
  'Gold Skeleton Mask': [
    'Orange Goggles',
    'Male Glow Glasses',
    'Reflective Glasses',
    'Cyclop Glasses',
    'Red Balaclava',
  ],
  'Gas Mask': [
    'Orange Goggles',
    'Cyclop Glasses',
    'Beanie',
    'Durag',
    'Helmet',
    'Shoulder Length Wavy',
    'Long Braids',
    'Long Blonde Streaks',
    'Long Locs',
    'Long Ponytail',
  ],
  'Black Bandana': ['Red Balaclava', 'Durag Helmet'],
  'Red Bandana': ['Red Balaclava', 'Durag Helmet'],
  'Red Blaclava': [
    'Male Glow Glasses',
    'Orange Goggles',
    'Cyclop Glasses',
    'Reflective Glasses',
    'Black Bandana',
    'Black Skeleton Mask',
    'Gold Skeleton Mask',
    'Male Black Jacket',
    'Diamond-Glasses',
    'Eye-Patch',
    'Metal Shades',
    'Red Bandana',
    'Gas Mask',
    'Long Beard',
    'Joint',
    'Male Cigarette',
  ],
  'Open Hoodie': ['Afro',
    'Backwards-Cap',
    'Beanie',
    'Durag',
    'Gold-Headpiece',
    'Half-Color-Locs',
    'Helmet',
    'Kings-Crown',
    'Long-Blonde-Streaks',
    'Long-Braids',
    'Long Locs',
    'Long-Ponytail',
    'Male Goggles',
    'Male Headphones',
    'Male-Horns',
    'Red Balaclava',
    'Red-Man-Bun',
    'Short Cut',
    'Short Wavy',
    'Shoulder-Length Wavy',
    'Slicked-Back',
    'Spiked',
    'White-Pixie-Cut',
    'White-Short-Locs',
    'White-Streaks-Short',],
  'Tribal Paint': [
    'Reflective Glasses',
    'Red Lazer',
    'Orange Goggles',
    'Male Glow Goggles',
    'Male Cyborg-Eye',
    'Eye-Patch',
    'Cyclop Glasses',
  ],
  'Male Black Cyber Jaw': [
    'Reflective Glasses',
    'Orange Goggles',
    'Metal Shades',
    'Male Glow Glasses',
  ],
  'Afro': [
    'Reflective Glasses',
    'Orange Goggles',
    'Male Glow Glasses',
    'Red Bandana',
    'Black Bandana',
  ],
  'Male Goggles': [
    'Reflective Glasses',
    'Orange Goggles',
    ' Male Glow Glasses',
    'Cyclop Glasses',
  ],
  'Orange Goggles': ['Long Ponytail', 'Gold Headpiece'],
};

module.exports.Female = {
  'Black Skeleton Mask': [
    'Orange Goggles',
    'Pink Eyes With Bandaid',
    'Female Glow Glasses',
    'Reflective Glasses',
    'Cyclop Glasses',
    'Black Balaclava',
  ],

  'Gold Skeleton Mask': [
    'Orange Goggles',
    'Pink Eyes With Bandaid',
    'Female Glow Glasses',
    'Reflective Glasses',
    'Cyclop Glasses',
    'Black Balaclava',
  ],

  'Gas-Mask': [
    'Female Glow Glasses',
    'Orange Goggles',
    'Cyclop Glasses',
    'Big-Curly',
    'Black Balaclava',
    'Blonde-Front',
    'Devil-Horns',
    'Blonde-Pin-Curls',
    'Half Up Half Down',
    'Half-Color-Ponytails',
    'Helmet',
    'Locs',
    'Long-Wavy',
    'One Braid',
    'Purple-With-Braids',
    'Red Hair-Horns',
    'Snakes',
    'White-Streaks',
    'Blue Goggles',
    'Queens Crown',
    'Big-Pink',
    'Angel-Halo',
    'Female Headphones',
    'Blonde-Front',
  ],

  'Black Bandana': [
    'Big-Curly',
    'Black Balaclava',
    'Blonde-Front',
    'Devil-Horns',
    'Blonde-Pin-Curls',
    'Half Up Half Down',
    'Half-Color-Ponytails',
    'Helmet',
    'Locs',
    'Long-Wavy',
    'One Braid',
    'Purple-With-Braids',
    'Red Hair-Horns',
    'Snakes',
    'White-Streaks',
  ],

  'Red Bandana': [
    'Big-Curly',
    'Black Balaclava',
    'Blonde-Front',
    'Devil-Horns',
    'Blonde-Pin-Curls',
    'Half Up Half Down',
    'Half-Color-Ponytails',
    'Helmet',
    'Locs',
    'Long-Wavy',
    'One Braid',
    'Purple-With-Braids',
    'Red Hair-Horns',
    'Snakes',
    'White-Streaks',
  ],

  'Black Balaclava': [
    'Orange Goggles',
    'Female Glow Glasses',
    'Cyclop Glasses',
    'Reflective Glasses',
    'Blunt',
    'Female Cigarette',
    'Bubblegum',
    'Red Bandana',
    'Tongue Ring',
    'Pink Lips With Sucker',
    'Red Lips With Sucker',
    'Gas-Mask',
    'Female Black-Jacket',
    'Black Bandana',
    'Black Skeleton Mask',
    'Gold Skeleton Mask',
  ],

  'Female Black Cyber Jaw': [
    'Reflective Glasses',
    'Orange Goggles',
    'Female Glow Glasses',
  ],
};
