module.exports.data =
{

  'Black Public Stalls': { counter: 0, limit: 650 },
  'Black Shower': { counter: 0, limit: 650 },
  'Black Tile': { counter: 0, limit: 650 },
  'Bloody': { counter: 0, limit: 1250 },
  'Graffiti': { counter: 0, limit: 1250 },
  'Green Tile': { counter: 0, limit: 650 },
  'Grey Public Stalls': { counter: 0, limit: 650 },
  'Grey Shower': { counter: 0, limit: 650 },
  'Light Blue Tile': { counter: 0, limit: 650 },
  'Metallic City View': { counter: 0, limit: 2250 },
  'Purple Tile': { counter: 0, limit: 650 },
  'Rainbow Tile': { counter: 0, limit: 2250 },
  'Red Tile': { counter: 0, limit: 650 },
  'White City View': { counter: 0, limit: 2250 },
  'White Tile': { counter: 0, limit: 650 },
  Male: { counter: 0, limit: 5000 },
  Female: { counter: 0, limit: 5000 },
  'Blood Male': { counter: 0, limit: 1550 },
  'Chocolate Male': { counter: 0, limit: 3000 },
  'Code Blue Male': { counter: 0, limit: 150 },
  'Fawn Male': { counter: 0, limit: 3000 },
  'Ghost Male': { counter: 0, limit: 1550 },
  'Gold Male': { counter: 0, limit: 50 },
  'Pale Male': { counter: 0, limit: 3000 },
  'Peru Male': { counter: 0, limit: 3000 },
  'Shadow Male': { counter: 0, limit: 1550 },
  'Silver Male': { counter: 0, limit: 100 },
  'Blessed Tattoo': { counter: 0, limit: 295 },
  'Blue-Eyes': { counter: 0, limit: 295 },
  'Cut-Eyebrow': { counter: 0, limit: 1500 },
  'Cyclop Glasses': { counter: 0, limit: 600 },
  'Diamond-Glasses': { counter: 0, limit: 600 },
  'Eye-Patch': { counter: 0, limit: 295 },
  'Male Cyborg-Eye': { counter: 0, limit: 600 },
  'Male Glow-Glasses': { counter: 0, limit: 250 },
  'Male Heterochromia': { counter: 0, limit: 295 },
  'Male Third-Eye': { counter: 0, limit: 295 },
  'Male Wink': { counter: 0, limit: 1500 },
  'Orange Goggless': { counter: 0, limit: 250 },
  'Metal shades': { counter: 0, limit: 295 },
  'Red Eyes': { counter: 0, limit: 295 },
  'Red Lazer': { counter: 0, limit: 600 },
  'Reflective Glasses': { counter: 0, limit: 250 },
  'Regular': { counter: 0, limit: 1500 },
  'Rockstar': { counter: 0, limit: 295 },
  'Scar': { counter: 0, limit: 295 },
  'Side Eye': { counter: 0, limit: 1500 },
  'Afro': { counter: 0, limit: 3275 },
  'Backwards-Cap': { counter: 0, limit: 800 },
  'Beanie': { counter: 0, limit: 375 },
  'Durag': { counter: 0, limit: 375 },
  'Gold-Headpiece': { counter: 0, limit: 150 },
  'Half-Color-Locs': { counter: 0, limit: 800 },
  'Helmet': { counter: 0, limit: 375 },
  'Kings-Crown': { counter: 0, limit: 150 },
  'Long-Blonde-Streaks': { counter: 0, limit: 3275 },
  'Long-Braids': { counter: 0, limit: 3275 },
  'Long Locs': { counter: 0, limit: 3275 },
  'Long-Ponytail': { counter: 0, limit: 3275 },
  'Male Goggles': { counter: 0, limit: 800 },
  'Male Headphones': { counter: 0, limit: 350 },
  'Male-Horns': { counter: 0, limit: 350 },
  'Red Balaclava': { counter: 0, limit: 50 },
  'Red-Man-Bun': { counter: 0, limit: 3275 },
  'Short Cut': { counter: 0, limit: 3275 },
  'Short Wavy': { counter: 0, limit: 3275 },
  'Shoulder-Length Wavy': { counter: 0, limit: 3275 },
  'Slicked-Back': { counter: 0, limit: 3275 },
  'Spiked': { counter: 0, limit: 800 },
  'White-Pixie-Cut': { counter: 0, limit: 3275 },
  'White-Short-Locs': { counter: 0, limit: 800 },
  'White-Streaks-Short': { counter: 0, limit: 3275 },
  'Black Bandana': { counter: 0, limit: 150 },
  'Black Skeleton Mask': { counter: 0, limit: 3275 },
  'Chin Strap': { counter: 0, limit: 3275 },
  'Closed': { counter: 0, limit: 3275 },
  'Full Beard': { counter: 0, limit: 3275 },
  'Gas-Mask': { counter: 0, limit: 25 },
  'Goatee': { counter: 0, limit: 3275 },
  'Gold Skeleton Mask': { counter: 0, limit: 3275 },
  'Joint': { counter: 0, limit: 3275 },
  'Long Beard': { counter: 0, limit: 3275 },
  'Male Big Grin': { counter: 0, limit: 3275 },
  'Male Biting Lip': { counter: 0, limit: 3275 },
  'Male Black Cyber Jaw': { counter: 0, limit: 3275 },
  'Male Braceface': { counter: 0, limit: 3275 },
  'Male Cigarette': { counter: 0, limit: 3275 },
  'Male Gap Teeth': { counter: 0, limit: 3275 },
  'Male Gold Grillz': { counter: 0, limit: 3275 },
  'Male Missing Teeth': { counter: 0, limit: 3275 },
  'Male Rainbow Grillz': { counter: 0, limit: 3275 },
  'Male Red Robot Jaw': { counter: 0, limit: 3275 },
  'Male Silver Grillz': { counter: 0, limit: 3275 },
  'Male Vampire': { counter: 0, limit: 3275 },
  'Metal-Chin': { counter: 0, limit: 3275 },
  'Open': { counter: 0, limit: 3275 },
  'Pointy Moustache': { counter: 0, limit: 3275 },
  'Red Bandana': { counter: 0, limit: 150 },
  'Stitched Up Male': { counter: 0, limit: 3275 },
  'Tribal Paint': { counter: 0, limit: 3275 },
  'Black-and-White-Half': { counter: 0, limit: 950 },
  'Body-Tattoos': { counter: 0, limit: 1000 },
  'Bow-Tie-and-Suspenders': { counter: 0, limit: 950 },
  'Bulletproof-Vest': { counter: 0, limit: 875 },
  'Classic Suit': { counter: 0, limit: 950 },
  'Coat': { counter: 0, limit: 750 },
  'Cyborg-Arm': { counter: 0, limit: 1000 },
  'Egyptian': { counter: 0, limit: 150 },
  'Jacket-On-Shoulders': { counter: 0, limit: 925 },
  'Kisses': { counter: 0, limit: 875 },
  'Male Black-Jacket': { counter: 0, limit: 950 },
  'Male Cyber Shirt': { counter: 0, limit: 875 },
  'Male Cyber-Suit': { counter: 0, limit: 350 },
  'Male-Cyberwear': { counter: 0, limit: 350 },
  'Male-Denim-Jacket': { counter: 0, limit: 950 },
  'Male Robotic-Arms': { counter: 0, limit: 1000 },
  'Male-Wings': { counter: 0, limit: 150 },
  'Ninja With Waves Tattoo': { counter: 0, limit: 875 },
  'Open Hoodie': { counter: 0, limit: 350 },
  'Phoenix': { counter: 0, limit: 1000 },
  'Pinstripe-Suit': { counter: 0, limit: 750 },
  'Pullover Hoodie': { counter: 0, limit: 925 },
  'Ripped-Shirt': { counter: 0, limit: 1000 },
  'Scars': { counter: 0, limit: 925 },
  'Snake-Tattoo-With-White-Tank': { counter: 0, limit: 750 },
  'Striped-Shirt': { counter: 0, limit: 925 },
  'Toga': { counter: 0, limit: 1000 },
  'Turtleneck-With-Chain': { counter: 0, limit: 750 },
  'Windbreaker': { counter: 0, limit: 925 },
  'Wrapped-Up-Male': { counter: 0, limit: 750 },
  'shirtless': { counter: 0, limit: 150 },
  'Blood Female': { counter: 0, limit: 1550 },
  'Chocolate Female': { counter: 0, limit: 3000 },
  'Fawn Female': { counter: 0, limit: 3000 },
  'Fuchsia Female': { counter: 0, limit: 150 },
  'Gold Female': { counter: 0, limit: 50 },
  'Ivory Female': { counter: 0, limit: 3000 },
  'Ivy Female': { counter: 0, limit: 1550 },
  'Mocha Female': { counter: 0, limit: 3000 },
  'Pale Female': { counter: 0, limit: 3000 },
  'Peru Female': { counter: 0, limit: 3000 },
  'Shadow Female': { counter: 0, limit: 1550 },
  'Silver Female': { counter: 0, limit: 100 },
  'Ghost Female': { counter: 0, limit: 1550 },
  'All White': { counter: 0, limit: 2650 },
  'Black Eye Paint': { counter: 0, limit: 2650 },
  'Brown': { counter: 0, limit: 1550 },
  'Closed': { counter: 0, limit: 1550 },
  'Cursed Tattoo': { counter: 0, limit: 2650 },
  'Cyclop Glasses': { counter: 0, limit: 550 },
  'Female Cyborg Eye': { counter: 0, limit: 550 },
  'Female Glow Glasses': { counter: 0, limit: 250 },
  'Female Heterochromia': { counter: 0, limit: 2650 },
  'Female Third Eye': { counter: 0, limit: 2650 },
  'Female Wink': { counter: 0, limit: 1550 },
  'Moon Cat Eyes': { counter: 0, limit: 2650 },
  'Orange Goggles': { counter: 0, limit: 250 },
  'Pink Eyes With Bandaid': { counter: 0, limit: 2650 },
  'Pink With Cat Eye': { counter: 0, limit: 1550 },
  'Red Lazer': { counter: 0, limit: 550 },
  'Reflective Glasses': { counter: 0, limit: 250 },
  'Rockstar': { counter: 0, limit: 2650 },
  'Rolling Eyes': { counter: 0, limit: 2650 },
  'Suprised': { counter: 0, limit: 1550 },
  'Angel-Halo': { counter: 0, limit: 375 },
  'Big-Curly': { counter: 0, limit: 3275 },
  'Big-Pink': { counter: 0, limit: 800 },
  'Black Balaclava': { counter: 0, limit: 50 },
  'Blonde-Front': { counter: 0, limit: 3275 },
  'Blonde-Pin-Curls': { counter: 0, limit: 800 },
  'Blue-Goggles': { counter: 0, limit: 800 },
  'Devil-Horns': { counter: 0, limit: 375 },
  'Double-Buns': { counter: 0, limit: 3275 },
  'Female Headphones': { counter: 0, limit: 350 },
  'Half Up Half Down': { counter: 0, limit: 3275 },
  'Half-Color-Ponytails': { counter: 0, limit: 800 },
  'Helmet': { counter: 0, limit: 375 },
  'High-Bun': { counter: 0, limit: 3275 },
  'Locs': { counter: 0, limit: 3275 },
  'Long-Wavy': { counter: 0, limit: 3275 },
  'One Braid': { counter: 0, limit: 3275 },
  'Purple-With-Braids': { counter: 0, limit: 3275 },
  'Queens Crown': { counter: 0, limit: 150 },
  'Red Hair-Horns': { counter: 0, limit: 350 },
  'Side Pony With Bangs': { counter: 0, limit: 3275 },
  'Snakes': { counter: 0, limit: 150 },
  'Spiked': { counter: 0, limit: 800 },
  'White-Pixie-Cut': { counter: 0, limit: 3275 },
  'White-Streaks': { counter: 0, limit: 3275 },
  'Black Bandana': { counter: 0, limit: 175 },
  'Black Skeleton Mask': { counter: 0, limit: 150 },
  'Blunt': { counter: 0, limit: 1350 },
  'Bubblegum': { counter: 0, limit: 1200 },
  'Female Big Grin': { counter: 0, limit: 1250 },
  'Female Biting Lip': { counter: 0, limit: 1250 },
  //'Female Black Cyber Jaw': { counter: 0, limit:  },
  'Female Braceface': { counter: 0, limit: 1200 },
  'Female Cigarette': { counter: 0, limit: 1350 },
  'Female Gap Teeth': { counter: 0, limit: 1250 },
  'Female Gold Grillz': { counter: 0, limit: 1350 },
  'Female Missing Teeth': { counter: 0, limit: 1350 },
  'Female Rainbow Grillz': { counter: 0, limit: 1350 },
  'Female Red-Robot-Jaw': { counter: 0, limit: 750 },
  'Female Silver Grillz': { counter: 0, limit: 1350 },
  'Female Vampire': { counter: 0, limit: 1350 },
  'Gas-Mask': { counter: 0, limit: 25 },
  'Gold Cyber Jaw': { counter: 0, limit: 750 },
  'Gold Skeleton Mask': { counter: 0, limit: 100 },
  'Juicy Lips': { counter: 0, limit: 1250 },
  'Lip Rings': { counter: 0, limit: 1250 },
  'Pink Lips With Sucker': { counter: 0, limit: 1200 },
  'Red Bandana': { counter: 0, limit: 175 },
  'Red Lips With Sucker': { counter: 0, limit: 1200 },
  'Slightly Open': { counter: 0, limit: 1250 },
  //'Stitched Up Female': { counter: 0, limit: 750 },
  'Tongue Out': { counter: 0, limit: 1250 },
  'Tongue Ring': { counter: 0, limit: 1200 },
  'Tribal': { counter: 0, limit: 1200 },
  'Black-and-White-Tie-Up': { counter: 0, limit: 950 },
  'Black-Dress-With-Choker': { counter: 0, limit: 750 },
  //'Detachable-Sleeve-Top': { counter: 0, limit:1000},
  'Diamond-Bralette': { counter: 0, limit: 150 },
  'Female Black-Jacket': { counter: 0, limit: 950 },
  'Female Cyber Shirt': { counter: 0, limit: 875 },
  'Female Cyber Suit': { counter: 0, limit: 350 },
  'Female Cybergear': { counter: 0, limit: 350 },
  'Female Denim-Jacket': { counter: 0, limit: 875 },
  'Female Robotic-Arms': { counter: 0, limit: 1000 },
  'Green-One-Sleeve': { counter: 0, limit: 925 },
  'Green-Star-Top': { counter: 0, limit: 1000 },
  'Halter Top': { counter: 0, limit: 950 },
  'Leather-Corset': { counter: 0, limit: 925 },
  'Mesh-Tank': { counter: 0, limit: 1000 },
  'Moto Jacket': { counter: 0, limit: 950 },
  'Ninja-With-Dragon-Tattoo': { counter: 0, limit: 875 },
  'Orange-Bandeau-With-Tats': { counter: 0, limit: 950 },
  'Pink-Bubble-Coat': { counter: 0, limit: 350 },
  'Puffy-Shoulder-Dress': { counter: 0, limit: 750 },
  'Purple-Cross-Tank': { counter: 0, limit: 925 },
  'Red-Glitter-Dress': { counter: 0, limit: 875 },
  'Scales': { counter: 0, limit: 1000 },
  'Silver Mesh Top': { counter: 0, limit: 925 },
  'Thick-Mesh-Long-Sleeve': { counter: 0, limit: 1000 },
  'Tiger-Print-Top': { counter: 0, limit: 925 },
  'Tiger-Tattoo-with-White-Camisole': { counter: 0, limit: 750 },
  //'Wings': { counter: 0, limit:},
  'Wrapped-Up': { counter: 0, limit: 750 },
  'Yellow-Bodysuit': { counter: 0, limit: 750 },
}