module.exports.background = [
  'Black Public Stalls',
  'Black Shower',
  'Black Tile',
  'Graffiti',
  'Green Tile',
  'Grey Public Stalls',
  'Grey Shower',
  'Light Blue Tile',
  'Metallic City View',
  'Purple Tile',
  'Rainbow Tile',
  'Red Tile',
  'White Tile',
];

module.exports.Male_Skin = [
  'Blood Male',
  'Chocolate Male',
  'Code Blue Male',
  'Fawn Male',
  'Ghost Male',
  'Gold Male',
  'Pale Male',
  'Peru Male',
  'Shadow Male',
  'Silver Male',
];

module.exports.Male_Eyes = [
  'Blessed Tattoo',
  'Blue-Eyes',
  'Cut-Eyebrow',
  'Cyclop Glasses',
  'Diamond-Glasses',
  'Eye-Patch',
  'Male Cyborg-Eye',
  'Male Glow-Glasses',
  'Male Heterochromia',
  'Male Third-Eye',
  'Male Wink',
  'Orange Goggles',
  'Metal shades',
  'Red Eyes',
  'Red Lazer',
  'Reflective Glasses',
  'Regular',
  'Rockstar',
  'Scar',
  'Side Eye',
];

module.exports.Male_Hairs = [
  'Afro',
  'Backwards-Cap',
  'Beanie',
  'Durag',
  'Gold-Headpiece',
  'Half-Color-Locs',
  'Helmet',
  'Kings-Crown',
  'Long-Blonde-Streaks',
  'Long-Braids',
  'Long Locs',
  'Long-Ponytail',
  'Male Goggles',
  'Male Headphones',
  'Male-Horns',
  'Red Balaclava',
  'Red-Man-Bun',
  'Short Cut',
  'Short Wavy',
  'Shoulder-Length Wavy',
  'Slicked-Back',
  'Spiked',
  'White-Pixie-Cut',
  'White-Short-Locs',
  'White-Streaks-Short',
];
module.exports.Male_Mouths = [
  'Black Bandana',
  'Black Skeleton Mask',
  'Chin Strap',
  'Closed',
  'Full Beard',
  'Gas-Mask',
  'Goatee',
  'Gold Skeleton Mask',
  'Joint',
  'Long Beard',
  'Male Big Grin',
  'Male Biting Lip',
  'Male Black Cyber Jaw',
  'Male Braceface',
  'Male Cigarette',
  'Male Gap Teeth',
  'Male Gold Grillz',
  'Male Missing Teeth',
  'Male Rainbow Grillz',
  'Male Red Robot Jaw',
  'Male Silver Grillz',
  'Male Vampire',
  'Metal-Chin',
  'Open',
  'Pointy Moustache',
  'Red Bandana',
  'Stitched Up Male',
  'Tribal Paint',
];

module.exports.Male_Outfit = [
  'Black-and-White-Half',
  'Body-Tattoos',
  'Bow-Tie-and-Suspenders',
  'Bulletproof-Vest',
  'Classic Suit',
  'Coat',
  'Cyborg-Arm',
  'Egyptian',
  'Jacket-On-Shoulders',
  'Kisses',
  'Male Black-Jacket',
  'Male Cyber Shirt',
  'Male Cyber-Suit',
  'Male-Cyberwear',
  'Male-Denim-Jacket',
  'Male Robotic-Arms',
  'Male-Wings',
  'Ninja With Waves Tattoo',
  'Open Hoodie',
  'Phoenix',
  'Pinstripe-Suit',
  'Pullover Hoodie',
  'Ripped-Shirt',
  'Scars',
  'Snake-Tattoo-With-White-Tank',
  'Striped-Shirt',
  'Toga',
  'Turtleneck-With-Chain',
  'Windbreaker',
  'Wrapped-Up-Male',
  'shirtless',
];

module.exports.Female_Skin = [
  'Blood Female',
  'Chocolate Female',
  'Fawn Female',
  'Fuchsia Female',
  'Gold Female',
  'Ivory Female',
  'Ivy Female',
  'Mocha Female',
  'Pale Female',
  'Peru Female',
  'Shadow Female',
  'Silver Female',
  'Ghost Female',
];

module.exports.Female_Eyes = [
  'All White',
  'Black Eye Paint',
  'Brown',
  'Closed',
  'Cursed Tattoo',
  'Cyclop Glasses',
  'Female Cyborg Eye',
  'Female Glow Glasses',
  'Female Heterochromia',
  'Female Third Eye',
  'Female Wink',
  'Moon Cat Eyes',
  'Orange Goggles',
  'Pink Eyes With Bandaid',
  'Pink With Cat Eye',
  'Red Lazer',
  'Reflective Glasses',
  'Rockstar',
  'Rolling Eyes',
  'Suprised',
];

module.exports.Female_Hairs = [
  'Angel-Halo',
  'Big-Curly',
  'Big-Pink',
  'Black Balaclava',
  'Blonde-Front',
  'Blonde-Pin-Curls',
  'Blue-Goggles',
  'Devil-Horns',
  'Double-Buns',
  'Female Headphones',
  'Half Up Half Down',
  'Half-Color-Ponytails',
  'Helmet',
  'High-Bun',
  'Locs',
  'Long-Wavy',
  'One Braid',
  'Purple-With-Braids',
  'Queens Crown',
  'Red Hair-Horns',
  'Side Pony With Bangs',
  'Snakes',
  'Spiked',
  'White-Pixie-Cut',
  'White-Streaks',
];

module.exports.Female_Mouths = [
  'Black Bandana',
  'Black Skeleton Mask',
  'Blunt',
  'Bubblegum',
  'Female Big Grin',
  'Female Biting Lip',
  //'Female Black Cyber Jaw',
  'Female Braceface',
  'Female Cigarette',
  'Female Gap Teeth',
  'Female Gold Grillz',
  'Female Missing Teeth',
  'Female Rainbow Grillz',
  'Female Red-Robot-Jaw',
  'Female Silver Grillz',
  'Female Vampire',
  'Gas-Mask',
  'Gold Cyber Jaw',
  'Gold Skeleton Mask',
  'Juicy Lips',
  'Lip Rings',
  'Pink Lips With Sucker',
  'Red Bandana',
  'Red Lips With Sucker',
  'Slightly Open',
  //'Stitched Up Female',
  'Tongue Out',
  'Tongue Ring',
  'Tribal',
  'Bloody',
];

module.exports.Female_Oufit = [
  'Black-and-White-Tie-Up',
  'Black-Dress-With-Choker',
  //'Detachable-Sleeve-Top',
  'Diamond-Bralette',
  'Female Black-Jacket',
  'Female Cyber Shirt',
  'Female Cyber Suit',
  'Female Cybergear',
  'Female Denim-Jacket',
  'Female Robotic-Arms',
  'Green-One-Sleeve',
  'Green-Star-Top',
  'Halter Top',
  'Leather-Corset',
  'Mesh-Tank',
  'Moto Jacket',
  'Ninja-With-Dragon-Tattoo',
  'Orange-Bandeau-With-Tats',
  'Pink-Bubble-Coat',
  'Puffy-Shoulder-Dress',
  'Purple-Cross-Tank',
  'Red-Glitter-Dress',
  'Scales',
  'Silver Mesh Top',
  'Thick-Mesh-Long-Sleeve',
  'Tiger-Print-Top',
  'Tiger-Tattoo-with-White-Camisole',
  //'Wings',
  'Wrapped-Up',
  'Yellow-Bodysuit',
];
